### ISSUE TITLE
"Error: The voice connection is not established due to missing session id"

### ISSUE THREAD

**Issue by Rykian** [Deivu/Shoukaku#116]
Hello,

I'm using the last version of Shoukaku (npm 3.2.2) with Node 18.12.1 and Lavalink (3.6.2), but when I'm using the node.joinChannel I've got this error:
```
Error: The voice connection is not established due to missing session id
    at Connection.connect (node_modules/shoukaku/src/guild/Connection.ts:161:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Node.joinChannel (node_modules/shoukaku/src/node/Node.ts:244:13)
    at MusicService.join (src/music/service.ts:92:20)
```

and on Lavalink side:
```
2022-12-16 18:20:33.934  INFO 37917 --- [  XNIO-1 I/O-12] lavalink.server.io.SocketServer          : Connection closed from /[0:0:0:0:0:0:0:1]:50349 -- CloseStatus[code=1006, reason=]
2022-12-16 18:20:33.935  INFO 37917 --- [  XNIO-1 I/O-12] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
```

The bot is joining the channel, but there is no sound output.

I'm using this code (interaction var comes from an interaction with a slash command):

```javascript
const shoukaku = new Shoukaku(
  new Connectors.DiscordJS(this.client.client),
  [{ name: 'Local', url: 'localhost:2333', auth: 'youshallnotpass' }],
);
shoukaku.on('error', (_, error) => console.error(error));

const node = shoukaku.getNode();
if (!node) return;
const result = await node.rest.resolve('ytsearch:never gonna give you up');
if (!result?.tracks.length) return;

const metadata = result.tracks.shift();
const channels = await interaction.guild.channels.fetch();
const channel = channels.find((channel) => {
  if (!(channel.type == ChannelType.GuildVoice)) return;
  return channel.members.find(
    (member) => member.user.id == interaction.member.user.id,
  );
});

if (!channel) return;

const player = await node.joinChannel({
  guildId: interaction.guildId,
  channelId: channel.id,
  shardId: 0,
});

player.playTrack({ track: metadata.track }).setVolume(0.5);
```

Any idea why?

**Comment by Rykian** [comment]
Found the problem. I'm logging in before Shoukaku's initialization, so I needed to add the intent `GatewayIntentBits.GuildVoiceStates` in client Initialization.
